# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".
#
# Makefile for the network assignment
#    Defines set up assuming this assignment is done last 
#
# Copyright (c) 1992 The Regents of the University of California.
# All rights reserved.  See copyright.h for copyright notice and limitation 
# of liability and disclaimer of warranty provisions.

ifndef MAKEFILE_NETWORK
define MAKEFILE_NETWORK
yes
endef

# To change the order of assignments, alter the follow includes as
# appropriate.

include ../threads/Makefile.local
include ../userprog/Makefile.local
include ../vm/Makefile.local
include ../filesys/Makefile.local
include ../network/Makefile.local

include ../Makefile.dep
include ../Makefile.common

endif #MAKEFILE_NETWORK